export const FETCH_CUSTOMERS_RESQUEST = "FETCH_CUSTOMERS_RESQUEST";
export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMERS_FAILURE = "FETCH_CUSTOMERS_FAILURE";

export const FETCH_CUSTOMERSBYID_RESQUEST = "FETCH_CUSTOMERSBYID_RESQUEST";
export const FETCH_CUSTOMERSBYID_SUCCESS = "FETCH_CUSTOMERSBYID_SUCCESS";
export const FETCH_CUSTOMERSBYID_FAILURE = "FETCH_CUSTOMERSBYID_FAILURE";