export const VIEW_BOOKED_TRIPS_REQUEST = "VIEW_BOOKED_TRIPS_REQUEST"
export const VIEW_BOOKED_TRIPS_SUCCESS = "VIEW_BOOKED_TRIPS_SUCCESS"
export const VIEW_BOOKED_TRIPS_FAILURE = "VIEW_BOOKED_TRIPS_FAILURE"